lab10test: lab_10.o lab_10_unit_test.o
	g++ -Wall -g -o lab10 lab_10.o lab_10_unit_test.o

lab10: lab_10.cpp
	g++ -Wall -g -c lab_10.cpp
	
lab10unittest: lab_10_unit_test.cpp
	g++ -Wall -g -c lab_10_unit_test.cpp