sllisttest: sl_node.o lab_16_unit_test.o sl_list.o
	g++ -Wall -g -o sllist sl_node.o sl_list.o lab_16_unit_test.o

slnode: sl_node.cpp
	g++ -Wall -g -c sl_node.cpp

sllist: sl_list.cpp
	g++ -Wall -g -c sl_list.cpp

lab16unittest: lab_16_unit_test.cpp
	g++ -Wall -g -c lab_16_unit_test.cpp