lab15test: sl_node.o lab_15_unit_test.o
	g++ -Wall -g -o lab15 sl_node.o lab_15_unit_test.o

lab15: sl_node.cpp
	g++ -Wall -g -c sl_node.cpp
	
lab15unittest: lab_15_unit_test.cpp
	g++ -Wall -g -c lab_15_unit_test.cpp