lab14test: lab_14.o lab_14_unit_test.o
	g++ -Wall -g -o lab14 lab_14.o lab_14_unit_test.o

lab14: lab_14.cpp
	g++ -Wall -g -c lab_14.cpp
	
lab14unittest: lab_14_unit_test.cpp
	g++ -Wall -g -c lab_14_unit_test.cpp