lab20test: lab_22.o lab_22_unit_test.o
	g++ -Wall -g -o lab20 lab_22.o lab_22_unit_test.o

lab20: lab_22.cpp
	g++ -Wall -g -c lab_22.cpp
	
lab20unittest: lab_22_unit_test.cpp
	g++ -Wall -g -c lab_22_unit_test.cpp