bstnodetest: bst_node.o bst_node_unit_test.o
	g++ -Wall -g -o bstnode bst_node.o bst_node_unit_test.o

bstnode: bst_node.cpp
	g++ -Wall -g -c bst_node.cpp
	
bstnodeunittest: bst_node_unit_test.cpp
	g++ -Wall -g -c bst_node_unit_test.cpp