lab15test: sorting.o lab_15_unit_test.o
	g++ -Wall -g -o lab15 sorting.o lab_15_unit_test.o

lab15: sorting.cpp
	g++ -Wall -g -c sorting.cpp
	
lab15unittest: lab_15_unit_test.cpp
	g++ -Wall -g -c lab_15_unit_test.cpp