bstreetest: bst_node.o lab_25_unit_test.o bs_tree.o
	g++ -Wall -g -o bstree bst_node.o bs_tree.o lab_25_unit_test.o

bstnode: bst_node.cpp
	g++ -Wall -g -c bst_node.cpp

bstree: bs_tree.cpp
	g++ -Wall -g -c bs_tree.cpp

lab25unittest: lab_25_unit_test.cpp
	g++ -Wall -g -c lab_25_unit_test.cpp